name: Tests

on: [push]

jobs:
  build-latest:
    name: Test on Latest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Test
        run: make test

  build-stable:
    name: Build on 1.53.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.53.0
          profile: minimal
          override: true
      - name: Test
        run: cargo check --all-features
